### ISSUE TITLE
您好，想问一些代码的问题

### ISSUE THREAD

**Issue by zhangjb233** [yyk-wew/F3Net#17]
您好，我是电信专业的学生，代码功底比较薄弱，在复现论文细节过程例如FAD模块的DCT图都出现了一些问题，请问您有微信吗，想请教一些问题

**Comment by yyk-wew** [comment]
您好，因为是公共issue不方便留微信，您可以给我发邮件，邮箱 yuanyike@zju.edu.cn

**Comment by zhangjb233** [comment]
&nbsp; 很高兴能收到您的来件。我是电子信息专业的本科生，最近在根据f3net论文以及您分析的代码进行相关的复现，遇到了很多代码上的问题。希望能得到您的一些帮助。&nbsp; 首先就是关于FAD模块。我想将对图片处理的过程可视化，像论文中那样显示DCT变换之后图片，以及分成三种平频带之后的图片。但我代码功底比较薄弱，我的做法是将FAD返回的out[3 12 299 299]，用torch.chunk函数进行分割，分成4块后再用squeeze函数压缩成三维的，最后转换回RGB三通道显示，但是得到的图片结果问题比较大。
&nbsp; 以及关于可学习滤波器的问题，想问一些可学习滤波器的自适应功能是怎么实现的呢。是放到了parameter中让网络自己去学习吗？
&nbsp; 由于知识还比较有限，问出来的问题可能也比较奇怪，如果您方便有空的话，希望得到您的解答。十分感谢
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Yike&nbsp;Yuan"; 
Date: 2022年5月8日(星期天) 中午1:12
To: "yyk-wew/F3Net"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [yyk-wew/F3Net] 您好，想问一些代码的问题 (Issue #17)

&nbsp;


 
您好，因为是公共issue不方便留微信，您可以给我发邮件，邮箱 ***@***.***

**Comment by yyk-wew** [comment]
> 首先就是关于FAD模块。我想将对图片处理的过程可视化

关于FAD模块的输出 `[12, 299, 299]`就是由高中低三个频段转换回的3通道RGB图像加上原本未经处理的3通道RGB图像构成了12通道，所以只需要chunk成4个部分不需要squeeze的。

可视化的结果不正常考虑可能是可视化的时候需要做一下归一化，因为高中低频段分割了之后原本像素分布应该是被破坏了的。

> 以及关于可学习滤波器的问题，想问一些可学习滤波器的自适应功能是怎么实现的呢。

是的，具体的实现是用一个和图像等大的可学习参数的mask，参与网络forward，通过BP对参数进行更新。
