### ISSUE TITLE
About the DCT Transform Matrix

### ISSUE THREAD

**Issue by DIY-Z** [yyk-wew/F3Net#27]
https://github.com/yyk-wew/F3Net/blob/01942ca3241c19c75fccc7fc3282554c147ceb43/models.py#L228-L230

上面的代码中的公式似乎与[mathworks链接](https://www.mathworks.com/help/images/discrete-cosine-transform.html)中的公式不太一样,
![2022-11-03 10-28-58屏幕截图](https://user-images.githubusercontent.com/59331765/199637093-97aaf135-17b2-4acf-850f-f09a3fe2e730.png)，个人觉得应该把代码中前面的括号去掉，如下:
```py
def DCT_mat(size):
    m = [[ np.sqrt(1./size) if i == 0 else np.sqrt(2./size) * np.cos((j + 0.5) * np.pi * i / size) for j in range(size)] for i in range(size)]
    return m
```

**Comment by zcajr** [comment]
不能去

**Comment by DIY-Z** [comment]
> https://github.com/yyk-wew/F3Net/blob/01942ca3241c19c75fccc7fc3282554c147ceb43/models.py#L228-L230
> 
> 上面的代码中的公式似乎与[mathworks链接](https://www.mathworks.com/help/images/discrete-cosine-transform.html)中的公式不太一样, ![2022-11-03 10-28-58屏幕截图](https://user-images.githubusercontent.com/59331765/199637093-97aaf135-17b2-4acf-850f-f09a3fe2e730.png)，个人觉得应该把代码中前面的括号去掉，如下:
> 
> ```python
> def DCT_mat(size):
>     m = [[ np.sqrt(1./size) if i == 0 else np.sqrt(2./size) * np.cos((j + 0.5) * np.pi * i / size) for j in range(size)] for i in range(size)]
>     return m
> ```

突然发现当i为0时后面的`np.cos((j + 0.5) * np.pi * i / size)`值为1（如果不去掉前面括号的话），所以去掉括号和不去掉括号得到的m其实是一样的。
