### ISSUE TITLE
Will some fake data not trained?

### ISSUE THREAD

**Issue by Yinjie-ZHENG** [yyk-wew/F3Net#6]
你好，我在拜读您的代码的时候发现您是通过分开real和fake两个dataloader来读取，并在一个batch中拼接起来以达到balancing的目的。不过在代码中我有一些不理解的地方望解答，在train.py中，我知道len_dataloader = dataloader_real.__len__()，这样会不会导致在您while循环内，其他多余的fake数据没有得到训练呢？（因为是real:fake是1:1的关系）
`        
while i < len_dataloader:
            
            i += 1
            model.total_steps += 1

            try:
                data_real = real_iter.next()
                data_fake = fake_iter.next()
            except StopIteration:
                break
            # -------------------------------------------------
`

**Comment by yyk-wew** [comment]
您好，首先解答您的问题，确实有可能存在”多余“的fake数据，但对训练不会产生很大的影响。

由于dataloader在初始化的时候设置了 _shuffle=True_ ，所以在每次结束一个 _i<len_dataloader_ 的循环之后，重新初始化读取real和fake数据的dataloader，此时从读取fake数据的dataloader中读取的batch经过shuffle和上一次循环读取的数据一般来说是不同的，每次随机重新取也基本能利用到绝大多数数据。

当然，从训练时需要利用每一张fake图像的角度出发，这段代码确实不严谨。应该设置一个条件，只有fake_iter遍历完整个dataset之后才重新初始化读取fake的dataloader，如下：

```python
while epoch < max_epoch:

        real_iter = iter(dataloader_real)

        while i < len_dataloader:
            
            i += 1
            model.total_steps += 1

            data_real = real_iter.next()
            
            try:  
                data_fake = fake_iter.next()
            except StopIteration:
                fake_iter = iter(dataloader_fake)
                data_fake = fake_iter.next()
```
这样就可以保证，在real图像被重复读取的时候遍历所有fake图像。

**Comment by Yinjie-ZHENG** [comment]
懂了，感谢您如此积极的回复！
